mindmap
  root((Cloud Strategy))
    Vision
      Increase Profitability
    Goals and Objectives
      Reduce IT Costs
    Desired Outcomes
      Reduce IT Costs by 20%
    Organizational Performance
      Increase Productivity
    Performance Management
      Use of KPIs